### ISSUE TITLE
How do I use files.upload?

### ISSUE THREAD

**Issue by Xorso** [StackStorm-Exchange/stackstorm-slack#14]
I can get files.upload with text that is not very large using the content variable. But I would like to know how to use the `file` variable to actually upload a larger set of string data. I have tried several methods and have not been able to get it to work.

I have:
1: Passed in the long string to file - failed
2: Created a tempfile and specified the file location in the file variable - failed

I have tried other iterations both those are the basic ones that I have used.

**Comment by LindsayHill** [comment]
Looks like this may not work with the generic `run.py` as it is set up today. Might need some additional handling to use the `files=` option with `requests()`
