### ISSUE TITLE
Should we remove unofficial actions?

### ISSUE THREAD

**Issue by shusugmt** [StackStorm-Exchange/stackstorm-slack#31]
It seems that `users.admin.invite` endpoint is not officially supported nor documented, as that  `slack_api_gen.py` does not generate an action metadata for it. But it is actually there and available for public use. Question is: should we keep this **not officially support** action? or remove?

Note: There seems to be several other *hidden and/or unsupported* API endpoints:
https://github.com/ErikKalkoken/slackApiDoc

**Comment by LindsayHill** [comment]
I believe we should keep those actions. `users.admin.invite` is very useful to a lot of people. 

I don't know exactly why Slack has those endpoints hidden.
