### ISSUE TITLE
chat.update text parameter marked required, not when only using attachment

### ISSUE THREAD

**Issue by namachieli** [StackStorm-Exchange/stackstorm-slack#41]
The `text` parameter in the action `slack.chat.update` is set to `required: true`. `slack.chat.postMessage` is not. 

Looking at the details for the corresponding methods in [slack's documentation](https://api.slack.com/methods/chat.update) the `text` parameter should only be required when not using any `attachments`

I propose that `required: true` should be removed and in the case where the action has neither specified, it be allowed to fail when the Slack API denies the request.

**Comment by namachieli** [comment]
Current work around is to send an empty string, but this causes `(edited)` to appear on a message that has no 'text'

**Comment by armab** [comment]
Fixed in https://github.com/StackStorm-Exchange/stackstorm-slack/pull/43

Thanks @namachieli for both bug-report and the fix!
