### ISSUE TITLE
Attachment not working in chat.postMessage

### ISSUE THREAD

**Issue by vovaled** [StackStorm-Exchange/stackstorm-slack#44]
I'm using your amazing pack, however, I cannot make the attachment to work with all the options I tried:

            name: "slack_ok"
            ref: "slack.chat.postMessage"
            parameters:
                 username: "username"
                 channel: "{{ slack_channel }}"
                 attachments: "{\"text\":\"test\"}"

tried:
                 attachments: "{\"text\":\"test\"}"
                 attachments: "{[\"text\":\"test\"]}"
                 attachments: "text: test"
                 attachments: "\"text\":\"test\""

In all scenarios I get no text:

st2.actions.python.SlackAction: ERROR    Failed to perform action chat.postMessage: {\"ok\":false,\"error\":\"no_text\"}                               (status code: 200)
None
Traceback (most recent call last):
  File \"/opt/stackstorm/runners/python_runner/python_runner/python_action_wrapper.py\", line 320, in <module>
    obj.run()
  File \"/opt/stackstorm/runners/python_runner/python_runner/python_action_wrapper.py\", line 179, in run
    output = action.run(**self._parameters)
  File \"/opt/stackstorm/packs/slack/actions/run.py\", line 16, in run
    return self._do_request(kwargs)
  File \"/opt/stackstorm/packs/slack/actions/run.py\", line 78, in _do_request
    raise Exception(failure_reason)
Exception: Failed to perform action chat.postMessage: {\"ok\":false,\"error\":\"no_text\"}                               (status code: 200)

Any help will be appreciated

**Comment by armab** [comment]
Take a look at this example of using `slack.chat.postMessage`:

https://github.com/StackStorm/st2ci/blob/master/actions/workflows/st2_pkg_upgrade_e2e_test.yaml#L316-L320

**Comment by blag** [comment]
According to the error message from Slack that you posted, you must specify `text` in your parameters - NOT just in `attachments`.

We should also update the `postMessage` action to accept either a string (that is a JSON string) or an array of objects for the `attachments` parameter, to match the Slack API.

Closing for now, but if you are still having issues, just drop a comment here and I'll reopen it.

**Comment by namachieli** [comment]
FWIW as long as there is something in the body of the attachment (title, author, etc) you dont have to fill out the literal field `text`

**Comment by namachieli** [comment]
The attachments field is already a string, FWIW.
```
  attachments:
    required: false
    type: string
```
Attachments has to be sent as a list though, so wrap your string in `[ ]`

```
        name: "slack_ok"
        ref: "slack.chat.postMessage"
        parameters:
             username: "username"
             channel: "{{ slack_channel }}"
             attachments: "[{\"text\":\"test\"}]"
```
