### ISSUE TITLE
Proposal: consistent action auto-generation

### ISSUE THREAD

**Issue by shusugmt** [StackStorm-Exchange/stackstorm-slack#47]
## Background

There is no up-to-date API spec for Slack Web API available in the world today. There are some places that OpenAPI based specs are published, but all of them are out of sync with the latest API, even those from official ones.

- https://api.slack.com/web#spec
- https://api.slack.com/specs/openapi/v2/slack_web.json
- https://github.com/slackapi/slack-api-specs

For e.g. `slack.chat.postMessage` should include `blocks` argument according to [the published html doc here](https://api.slack.com/methods/chat.postMessage), but it never appears in all of the above.

Quick look at https://github.com/slackapi/slack-api-specs/issues indicates that this repo seems to be abandoned?

So the only method we have left is scraping, which is exactly the way we are doing for now to auto-generate action meta yaml files. But this also have some problems.

Significant one is its unstableness of the page structure. When I run `slack_api_gen.py` today to apply updates on parameters to some actions, the action `description` fields become empty. After quick debugging, I found out that the html element previously used to fill in this field disappeared. And there seems no equivalent or good alternative for populating description.

The other major problem we have is the parameter type all marked as `string`. This is because the type is not clearly stated in the html doc, so we can't infer what type the parameter accepts. This makes users a bit confusing when passing Booelan-ish parameter. The action expects it passed in string type, so user need to pass `"True"` not `True`. The same thing happens to other types like numbers.

## Proposal

For short term, action description should be replaced with some fixed string like:
`This action is auto-generated. See https://api.slack.com/methods/chat.postMessage`
And never tries to fill in from their html page.

For next, it may worth trying to combine the scraping + (outdated) OpenAPI spec. First we scrape, at this time the action description is the fixed string suggested above and all the parameter types are marked as string. After this we can complement action description, parameter types and even parameter descriptions from OpenAPI spec. There are some missing parameters or even API endpoint itself in current OpenAPI spec, but we at least can cover them at scraping stage so they won't be missing.

In the future, hopefully we can count on OpenAPI spec that is up-to-date.

**Comment by nmaludy** [comment]
Closing in favor #55
