### ISSUE TITLE
Private Rooms Not Showing the channels.list Action

### ISSUE THREAD

**Issue by chavenor** [StackStorm-Exchange/stackstorm-slack#6]
It seems that the private channels are not coming through which is odd because the user I used the auth token has access to those rooms. 

Not sure if this is an expected result.

**Comment by LindsayHill** [comment]
Yes, that is an expected result. That action is using the channels.list Slack API.  Check https://api.slack.com/methods/channels.list

> This method returns a list of all channels in the team. This includes channels the caller is in, channels they are not currently in, and archived channels but does not include private channels. The number of (non-deactivated) members in each channel is also returned.
>
> To retrieve a list of private channels, use groups.list.
