### ISSUE TITLE
Slack Channel ID Search

### ISSUE THREAD

**Issue by jpavlav** [StackStorm-Exchange/stackstorm-slack#82]
Hey folks!

Recently I had need to find the ID of a channel based on it's name during some internal development at work. I'd be happy to add the action, but it's not something that the Slack API offers out of the box, so it wouldn't conform to the generated actions here.

**Comment by armab** [comment]
I think it's OK to commit a new action outside of the auto-generated content, so new Actions are very welcome!

Just add a note/reminder to the https://github.com/StackStorm-Exchange/stackstorm-slack#how-to-auto-generate-actions for someone auto-generating the content in the future so they'll include custom-added actions.

**Comment by jpavlav** [comment]
Nice! I'll see about getting a PR up this week hopefully.
